development:
  adapter: postgresql
  encoding: unicode
  host: 
  database: wait-for-it_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: 
  database: wait-for-it_test
  pool: 5


